# Generated by Django 2.2.6 on 2019-11-17 11:44

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to=teams.models.get_image_filename),
        ),
    ]
