# Generated by Django 2.2.6 on 2019-11-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='objective',
            field=models.CharField(blank=True, max_length=1, verbose_name='목적'),
        ),
    ]
