# Generated by Django 2.2.6 on 2019-11-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='recruit_count',
        ),
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='skills',
            field=models.ManyToManyField(related_name='teams', to='teams.Skill', verbose_name='스킬'),
        ),
    ]
