# Generated by Django 2.2.6 on 2019-11-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191116_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(related_name='teams', to='teams.Tag', verbose_name='태그'),
        ),
    ]
