# Generated by Django 2.2.6 on 2019-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191118_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/image/%Y/%m/%d/', verbose_name='이미지'),
        ),
    ]
