# Generated by Django 2.2.6 on 2019-11-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20191119_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_personnel',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='현재 인원'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_personnel',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='최대 인원'),
            preserve_default=False,
        ),
    ]
