# Generated by Django 2.2.6 on 2019-12-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
