# Generated by Django 2.2.6 on 2019-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20191212_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='teams', to='teams.Tag', verbose_name='태그'),
        ),
    ]
