# Generated by Django 2.2.6 on 2020-01-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20200101_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='current_personnel',
        ),
    ]
