# Generated by Django 2.2.6 on 2020-01-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_remove_team_current_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('waiting', '대기중'), ('expiry', '만료됨'), ('complete', '완됨')], default='waiting', max_length=10, verbose_name='상태'),
        ),
    ]
