# Generated by Django 2.2.6 on 2020-01-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kakao_chat_url',
            field=models.URLField(default='https://open.kakao.com/o/gbIUlwTbc'),
            preserve_default=False,
        ),
    ]
