# Generated by Django 2.2.6 on 2020-01-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting', '승인 대기'), ('expiry', '만료'), ('approved', '승인 완료'), ('refuse', '승인 거절')], default='waiting', max_length=10, verbose_name='상태'),
        ),
    ]
