# Generated by Django 2.2.6 on 2020-01-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200119_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting', '승인대기'), ('expiry', '만료'), ('approved', '승인완료'), ('refuse', '승인거절')], default='waiting', max_length=10, verbose_name='상태'),
        ),
    ]
