# Generated by Django 2.2.6 on 2019-11-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='깃허브 로그인 아이디')),
                ('avatar', models.URLField(verbose_name='아바타')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('languages', models.TextField(blank=True, verbose_name='언어')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_image/profile/%Y/%m/%d/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, verbose_name='별명'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.GithubProfile', verbose_name='프로필'),
        ),
    ]
