# Generated by Django 2.2.6 on 2019-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191114_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
    ]
